### ISSUE TITLE
Issue getting keys from some hubs

### ISSUE THREAD

**Issue by shauder** [michielpost/HueLightDJ#3]
I was able to use the setup page successfully for one but my other two are giving me an error.

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: invalid value, for parameter, lights
   at Q42.HueApi.HueClient.CreateGroupAsync(IEnumerable`1 lights, String name, Nullable`1 roomClass, GroupType groupType)
   at HueLightDJ.Web.Controllers.HomeController.Register(String ip) in /src/HueLightDJ.Web/Controllers/HomeController.cs:line 78
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)```

**Comment by michielpost** [comment]
Ah yes, I think I've seen that before. You probably need to upgrade the bridge to the latest firmware, that will fix it. You can use the official Hue app to trigger a bridge upgrade.

**Comment by shauder** [comment]
I thought so also but they are all on version Firmware: 1808300701.  I checked for updates and confirmed each bridge.  The bridges also have 1 motion sensor, 1 switch on each.  The one that works also has those also.  I have 10 or less color bulbs on each bridge (reason I got more).  I am using the bridges successfully in every other app I have (home-assistant.io, huedynamic, etc).

What else can I do/provide that would help?  Based on the line number the error is happening at it seems to error when creating the EntertainmentGroup through the API.  Perhaps its trying to add one of my other devices that is not a light? Meaning also that the other one that works just happens to only come upon lights in the first 10 objects?

**Comment by michielpost** [comment]
You can also create the Entertainment Group with the Philips Hue app and check if that works. Or use an existing entertainment group on the bridge.
It's not a requirement to create the group using HueLightDJ, if you create one yourself, just fill in the group number of the entertainment group in the config and it should work.

**Comment by shauder** [comment]
Yeah, I know you can make calls to the API itself to get the keys needed but was hoping to just use the Setup page and thought you may be interested in improving it.  I'll just close this and get the keys manually.
