### ISSUE TITLE
Cannot Get Key and EntertainmentKey in /setup

### ISSUE THREAD

**Issue by Eightloop** [michielpost/HueLightDJ#8]
Hello,

I am using the HueLightDJ containter. When navigation to /setup and clicking on "Press the button on the Hue Bridge and then preiss this button" button, I receive an error:

`An unhandled exception has occurred while executing the request.

      Q42.HueApi.LinkButtonNotPressedException: Link button not pressed

         at Q42.HueApi.LocalHueClient.RegisterAsync(String ip, String applicationName, String deviceName, Boolean generateClientKey)

         at Q42.HueApi.LocalHueClient.RegisterAsync(String applicationName, String deviceName, Boolean generateClientKey)

         at HueLightDJ.Web.Controllers.HomeController.Register(String ip) in /src/HueLightDJ.Web/Controllers/HomeController.cs:line 72

         at lambda_method163(Closure , Object )

         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)`

I am using the latest firmware on my Hue Bridge. And ideas what it could be? Excited to try HueLightDJ out!

**Comment by michielpost** [comment]
Is the IP under 'Bridge IPs found:' correct?
You should first press the button on your bridge and then the button on the webpage.

It will give you a json response, this json has to be added to the appsettings.json. I don't think you can do that using the Docker image. There is no automatic flow right now to do that for you.

You probably have to download the code and run it with a modified appsettings.json.

**Comment by Eightloop** [comment]
Thank you for the quick reply! The IP under 'Bridge IPs found:' is definitely correct and I have also pressed the bridge button first and then the button on the webpage.

I will see if I can get it to work using the code. Thanks again!
